name: "Deploy new portfolio"

on:
  push:
    tags: 
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t my-app:${{github.sha}} .
          docker tag my-app:${{github.sha}} aandrku/portfolio:latest

      - name: Push Docker image
        run: |
          docker push aandrku/portfolio:latest
