name: "Deploy new portfolio"

on:
  push:
    tags: 
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t portfolio:${{github.sha}} .
          docker tag portfolio:${{github.sha}} aandrku/portfolio:latest

      - name: Push Docker image
        run: |
          docker push aandrku/portfolio:latest

      - name: Set up the SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add to known hosts
        run: |
          ssh-keyscan -H 44.223.136.62 >> ~/.ssh/known_hosts
      - name: ssh into EC2 
        run: |
          ssh -v -i "~/.ssh/id_rsa" ubuntu@44.223.136.62 "echo 'Hello from EC2!' && uptime"
