name: Test Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23  # Specify your Go version

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t aandrku:portfolio .

    # Step 4: Change to the server directory
    - name: Change to server directory
      working-directory: ./server
      run: echo "Switched to server directory"

    # Step 5: Run go build
    - name: Run go build
      working-directory: ./server
      run: go build ./...

    # Step 6: Run go test
    - name: Run go test
      working-directory: ./server
      run: go test ./... -v

    # Step 7: Run golangci-lint
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: ./...
